### ISSUE TITLE
Example issue!

### ISSUE THREAD

**Issue by firetto** [arosnerd/SigmaCode#3]
This is the list of issues that needs to be fixed:

- Global warming
- Droughts
- Food crisis
- Poverty

These are the people that should be responsible for this:

1. Nikita K
2. Alex F

Here's our progress so far:

- [x] Cure cancer
- [ ] Solve global warming
- [ ] Revert all droughts
- [ ] Poverty
- [ ] Solve the food crisis

You can also reference commits: #2 

# Header

## Subheader

LOL!

**Comment by nikitakhesin** [comment]
I'm on it!
